# Generated by Django 5.0.1 on 2025-08-06 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("ROLLBACK", "Rollback"),
                            ("BULK_UPDATE", "Bulk Update"),
                            ("BULK_DELETE", "Bulk Delete"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("previous_values", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("can_rollback", models.BooleanField(default=True)),
                ("rollback_data", models.JSONField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_logs",
                        to="audit.auditlog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BulkOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("bulk_create", "Bulk Create"),
                            ("bulk_update", "Bulk Update"),
                            ("bulk_delete", "Bulk Delete"),
                            ("import", "Data Import"),
                            ("export", "Data Export"),
                            ("migration", "Data Migration"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("processed_items", models.PositiveIntegerField(default=0)),
                ("failed_items", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("audit_logs", models.ManyToManyField(blank=True, to="audit.auditlog")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_bulk_operations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("snapshot_data", models.JSONField()),
                ("snapshot_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Snapshot"),
                            ("manual", "Manual Snapshot"),
                            ("pre_bulk_operation", "Pre-Bulk Operation"),
                            ("pre_migration", "Pre-Migration"),
                            ("pre_deployment", "Pre-Deployment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_logs",
                    models.ManyToManyField(blank=True, to="audit.auditlog"),
                ),
            ],
            options={
                "db_table": "audit_snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_logs_content_b0ef47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_logs_user_id_88267f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="audit_logs_action_474804_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["request_id"], name="audit_logs_request_298ea7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkoperation",
            index=models.Index(
                fields=["operation_id"], name="audit_bulk__operati_4aedac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkoperation",
            index=models.Index(
                fields=["status", "created_at"], name="audit_bulk__status_c74705_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkoperation",
            index=models.Index(
                fields=["content_type", "operation_type"],
                name="audit_bulk__content_86ce98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelsnapshot",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_snaps_content_de91bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelsnapshot",
            index=models.Index(
                fields=["created_at", "snapshot_type"],
                name="audit_snaps_created_604af2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelsnapshot",
            index=models.Index(
                fields=["snapshot_hash"], name="audit_snaps_snapsho_70a6dc_idx"
            ),
        ),
    ]
